// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: continuation_type_wrapper.proto

package com.google.protos.youtube.api.innertube;

public final class ContinuationTypeWrapperOuterClass {
  private ContinuationTypeWrapperOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContinuationTypeWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.protos.youtube.api.innertube.ContinuationTypeWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string append_continuation = 15;</code>
     * @return Whether the appendContinuation field is set.
     */
    boolean hasAppendContinuation();
    /**
     * <code>optional string append_continuation = 15;</code>
     * @return The appendContinuation.
     */
    java.lang.String getAppendContinuation();
    /**
     * <code>optional string append_continuation = 15;</code>
     * @return The bytes for appendContinuation.
     */
    com.google.protobuf.ByteString
        getAppendContinuationBytes();

    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return Whether the reloadContinuation field is set.
     */
    boolean hasReloadContinuation();
    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return The reloadContinuation.
     */
    java.lang.String getReloadContinuation();
    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return The bytes for reloadContinuation.
     */
    com.google.protobuf.ByteString
        getReloadContinuationBytes();
  }
  /**
   * Protobuf type {@code com.google.protos.youtube.api.innertube.ContinuationTypeWrapper}
   */
  public static final class ContinuationTypeWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.protos.youtube.api.innertube.ContinuationTypeWrapper)
      ContinuationTypeWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContinuationTypeWrapper.newBuilder() to construct.
    private ContinuationTypeWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContinuationTypeWrapper() {
      appendContinuation_ = "";
      reloadContinuation_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContinuationTypeWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContinuationTypeWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              appendContinuation_ = s;
              break;
            }
            case 578: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              reloadContinuation_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.class, com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.Builder.class);
    }

    private int bitField0_;
    public static final int APPEND_CONTINUATION_FIELD_NUMBER = 15;
    private volatile java.lang.Object appendContinuation_;
    /**
     * <code>optional string append_continuation = 15;</code>
     * @return Whether the appendContinuation field is set.
     */
    @java.lang.Override
    public boolean hasAppendContinuation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string append_continuation = 15;</code>
     * @return The appendContinuation.
     */
    @java.lang.Override
    public java.lang.String getAppendContinuation() {
      java.lang.Object ref = appendContinuation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appendContinuation_ = s;
        return s;
      }
    }
    /**
     * <code>optional string append_continuation = 15;</code>
     * @return The bytes for appendContinuation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppendContinuationBytes() {
      java.lang.Object ref = appendContinuation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appendContinuation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELOAD_CONTINUATION_FIELD_NUMBER = 72;
    private volatile java.lang.Object reloadContinuation_;
    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return Whether the reloadContinuation field is set.
     */
    @java.lang.Override
    public boolean hasReloadContinuation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return The reloadContinuation.
     */
    @java.lang.Override
    public java.lang.String getReloadContinuation() {
      java.lang.Object ref = reloadContinuation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reloadContinuation_ = s;
        return s;
      }
    }
    /**
     * <code>optional string reload_continuation = 72;</code>
     * @return The bytes for reloadContinuation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReloadContinuationBytes() {
      java.lang.Object ref = reloadContinuation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reloadContinuation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, appendContinuation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 72, reloadContinuation_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, appendContinuation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(72, reloadContinuation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper)) {
        return super.equals(obj);
      }
      com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper other = (com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper) obj;

      if (hasAppendContinuation() != other.hasAppendContinuation()) return false;
      if (hasAppendContinuation()) {
        if (!getAppendContinuation()
            .equals(other.getAppendContinuation())) return false;
      }
      if (hasReloadContinuation() != other.hasReloadContinuation()) return false;
      if (hasReloadContinuation()) {
        if (!getReloadContinuation()
            .equals(other.getReloadContinuation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAppendContinuation()) {
        hash = (37 * hash) + APPEND_CONTINUATION_FIELD_NUMBER;
        hash = (53 * hash) + getAppendContinuation().hashCode();
      }
      if (hasReloadContinuation()) {
        hash = (37 * hash) + RELOAD_CONTINUATION_FIELD_NUMBER;
        hash = (53 * hash) + getReloadContinuation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.protos.youtube.api.innertube.ContinuationTypeWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.protos.youtube.api.innertube.ContinuationTypeWrapper)
        com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.class, com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.Builder.class);
      }

      // Construct using com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appendContinuation_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        reloadContinuation_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor;
      }

      @java.lang.Override
      public com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper getDefaultInstanceForType() {
        return com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper build() {
        com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper buildPartial() {
        com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper result = new com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appendContinuation_ = appendContinuation_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reloadContinuation_ = reloadContinuation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper) {
          return mergeFrom((com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper other) {
        if (other == com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper.getDefaultInstance()) return this;
        if (other.hasAppendContinuation()) {
          bitField0_ |= 0x00000001;
          appendContinuation_ = other.appendContinuation_;
          onChanged();
        }
        if (other.hasReloadContinuation()) {
          bitField0_ |= 0x00000002;
          reloadContinuation_ = other.reloadContinuation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appendContinuation_ = "";
      /**
       * <code>optional string append_continuation = 15;</code>
       * @return Whether the appendContinuation field is set.
       */
      public boolean hasAppendContinuation() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string append_continuation = 15;</code>
       * @return The appendContinuation.
       */
      public java.lang.String getAppendContinuation() {
        java.lang.Object ref = appendContinuation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appendContinuation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string append_continuation = 15;</code>
       * @return The bytes for appendContinuation.
       */
      public com.google.protobuf.ByteString
          getAppendContinuationBytes() {
        java.lang.Object ref = appendContinuation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appendContinuation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string append_continuation = 15;</code>
       * @param value The appendContinuation to set.
       * @return This builder for chaining.
       */
      public Builder setAppendContinuation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appendContinuation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string append_continuation = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppendContinuation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appendContinuation_ = getDefaultInstance().getAppendContinuation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string append_continuation = 15;</code>
       * @param value The bytes for appendContinuation to set.
       * @return This builder for chaining.
       */
      public Builder setAppendContinuationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        appendContinuation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reloadContinuation_ = "";
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @return Whether the reloadContinuation field is set.
       */
      public boolean hasReloadContinuation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @return The reloadContinuation.
       */
      public java.lang.String getReloadContinuation() {
        java.lang.Object ref = reloadContinuation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reloadContinuation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @return The bytes for reloadContinuation.
       */
      public com.google.protobuf.ByteString
          getReloadContinuationBytes() {
        java.lang.Object ref = reloadContinuation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reloadContinuation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @param value The reloadContinuation to set.
       * @return This builder for chaining.
       */
      public Builder setReloadContinuation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reloadContinuation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @return This builder for chaining.
       */
      public Builder clearReloadContinuation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reloadContinuation_ = getDefaultInstance().getReloadContinuation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reload_continuation = 72;</code>
       * @param value The bytes for reloadContinuation to set.
       * @return This builder for chaining.
       */
      public Builder setReloadContinuationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        reloadContinuation_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.protos.youtube.api.innertube.ContinuationTypeWrapper)
    }

    // @@protoc_insertion_point(class_scope:com.google.protos.youtube.api.innertube.ContinuationTypeWrapper)
    private static final com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper();
    }

    public static com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContinuationTypeWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ContinuationTypeWrapper>() {
      @java.lang.Override
      public ContinuationTypeWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContinuationTypeWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContinuationTypeWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContinuationTypeWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protos.youtube.api.innertube.ContinuationTypeWrapperOuterClass.ContinuationTypeWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037continuation_type_wrapper.proto\022\'com.g" +
      "oogle.protos.youtube.api.innertube\"\215\001\n\027C" +
      "ontinuationTypeWrapper\022 \n\023append_continu" +
      "ation\030\017 \001(\tH\000\210\001\001\022 \n\023reload_continuation\030" +
      "H \001(\tH\001\210\001\001B\026\n\024_append_continuationB\026\n\024_r" +
      "eload_continuationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_protos_youtube_api_innertube_ContinuationTypeWrapper_descriptor,
        new java.lang.String[] { "AppendContinuation", "ReloadContinuation", "AppendContinuation", "ReloadContinuation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
