<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: continuation_wrapper.proto

namespace GPBMetadata;

class ContinuationWrapper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BrowseContinuation::initOnce();
        $pool->internalAddGeneratedFile(
            '
»
continuation_wrapper.proto\'com.google.protos.youtube.api.innertube"y
ContinuationWrapperb
browse_continuationú’†& (2B.com.google.protos.youtube.api.innertube.BrowseContinuationWrapperbproto3'
        , true);

        static::$is_initialized = true;
    }
}

